export const data = {
  graphicProject: {
    id: 'ck9b9n8kw1x720720sjwwl1g7',
    createdAt: '2020-04-22T11:40:51.599Z',
    updatedAt: '2020-05-08T19:28:25.219Z',
    publishedAt: null,
    type: 'SOCIAL_MEDIA',
    title: 'Just another graphic project',
    copyright: 'NO_COPYRIGHT',
    alt: 'some alt text',
    descPublic: 'the public description',
    descInternal: 'the internal description',
    images: [
      {
        id: 'cka5di41430i10720v06c52ic',
        createdAt: '2020-05-13T13:21:56.183Z',
        updatedAt: '2020-05-13T13:25:12.933Z',
        title: '4_3_Serious_TW.jpg',
        filename: '4_3_Serious_TW.jpg',
        filesize: 297343,
        visibility: 'PUBLIC',
        url: '2020/04/commons.america.gov_ck9laaua62c2o0720577s3jto/4_3_Serious_TW.jpg',
        signedUrl: 'https://amgov-publisher-dev.s3.amazonaws.com/2020/04/commons.america.gov_ck9laaua62c2o0720577s3jto/4_3_Serious_TW.jpg?AWSAccessKeyId=accesskey&Expires=1589468486&Signature=BSnPgB%2FYTX0xmcf%2BFuf30euIczo%3D',
        style: {
          id: 'ck9h3koe426aa0720y421wmk3',
          name: 'Clean',
        },
        social: [
          {
            id: 'ck9h3m3g626bd07201gh712vk',
            name: 'Twitter',
          },
        ],
        language: {
          id: 'ck2lzfx710hkq07206thus6pt',
          languageCode: 'en',
          locale: 'en-us',
          textDirection: 'LTR',
          displayName: 'English',
          nativeName: 'English',
        },
        use: {
          id: 'ck2lzfx510hhj07205mal3e4l',
          name: 'Thumbnail/Cover Image',
        },
        quality: 'WEB',
        dimensions: {
          id: 'cka5di41m30i20720rvqjahzy',
          width: 1200,
          height: 675,
        },
      },
      {
        id: 'cka5di48r30ig072003dqjffb',
        createdAt: '2020-05-13T13:21:56.467Z',
        updatedAt: '2020-05-13T13:25:12.937Z',
        title: '4_3_Serious_FB.jpg',
        filename: '4_3_Serious_FB.jpg',
        filesize: 433851,
        visibility: 'PUBLIC',
        url: '2020/04/commons.america.gov_ck9laaua62c2o0720577s3jto/4_3_Serious_FB.jpg',
        signedUrl: 'https://amgov-publisher-dev.s3.amazonaws.com/2020/04/commons.america.gov_ck9laaua62c2o0720577s3jto/4_3_Serious_FB.jpg?AWSAccessKeyId=accesskey&Expires=1589468486&Signature=thesignature',
        style: {
          id: 'ck9h3kyb326ak0720wkbk01q6',
          name: 'Info/Stat',
        },
        social: [
          {
            id: 'ck9h3m9bl26bm0720rm69c60s',
            name: 'Facebook',
          },
        ],
        language: {
          id: 'ck2lzfx710hkq07206thus6pt',
          languageCode: 'en',
          locale: 'en-us',
          textDirection: 'LTR',
          displayName: 'English',
          nativeName: 'English',
        },
        use: {
          id: 'ck2lzfx510hhj07205mal3e4l',
          name: 'Thumbnail/Cover Image',
        },
        quality: 'WEB',
        dimensions: {
          id: 'cka5di49730ih0720o1u2m49y',
          width: 1200,
          height: 1200,
        },
      },
    ],
    assetPath: null,
    author: {
      id: 'ck2m042xo0rnp0720nb4gxjix',
      firstName: 'Edwin',
      lastName: 'Mah',
      email: 'mahe@america.gov',
    },
    team: {
      id: 'ck2qgfbku0ubh0720iwhkvuyn',
      name: 'GPA Editorial & Design',
      organization: 'Department of State',
    },
    status: 'DRAFT',
    visibility: 'PUBLIC',
    supportFiles: [
      {
        id: 'ck9jtsbvz291i0720by3crdcc',
        createdAt: '2020-04-28T11:26:50.874Z',
        updatedAt: '2020-05-06T12:04:52.123Z',
        url: null,
        filename: 's-secure-rights_shell.png',
        filetype: 'image/png',
        filesize: 29000,
        visibility: 'PUBLIC',
        use: null,
        language: {
          id: 'ck2lzfx710hkq07206thus6pt',
          languageCode: 'en',
          locale: 'en-us',
          textDirection: 'LTR',
          displayName: 'English',
          nativeName: 'English',
        },
      },
      {
        id: 'ck9jtu1gk292c0720novktaks',
        createdAt: '2020-04-28T11:28:10.723Z',
        updatedAt: '2020-05-06T12:04:41.699Z',
        url: null,
        filename: 's-secure-rights_arabic.psd',
        filetype: 'image/vnd.adobe.photoshop',
        filesize: 509000,
        visibility: 'PUBLIC',
        use: null,
        language: {
          id: 'ck2lzfx760hkt07200roop1ut',
          languageCode: 'ar',
          locale: 'ar',
          textDirection: 'RTL',
          displayName: 'Arabic',
          nativeName: 'العربية',
        },
      },
      {
        id: 'ck9jtuqhy292w07200tfpbkju',
        createdAt: '2020-04-28T11:28:43.173Z',
        updatedAt: '2020-05-06T12:04:17.325Z',
        url: null,
        filename: 's-secure-rights_asikaid_ksidn_kaslkdfiwnz_iqmshqusm_kwspamdisa_sucms_english.psd',
        filetype: 'image/vnd.adobe.photoshop',
        filesize: 509000,
        visibility: 'PUBLIC',
        use: null,
        language: {
          id: 'ck2lzfx710hkq07206thus6pt',
          languageCode: 'en',
          locale: 'en-us',
          textDirection: 'LTR',
          displayName: 'English',
          nativeName: 'English',
        },
      },
      {
        id: 'ck9jtwa1v293h0720rbd1vdjr',
        createdAt: '2020-04-28T11:29:55.168Z',
        updatedAt: '2020-05-06T12:04:01.749Z',
        url: null,
        filename: 's-secure-rights_transcript.docx',
        filetype: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        filesize: 9000,
        visibility: 'PUBLIC',
        use: null,
        language: {
          id: 'ck2lzfx710hkq07206thus6pt',
          languageCode: 'en',
          locale: 'en-us',
          textDirection: 'LTR',
          displayName: 'English',
          nativeName: 'English',
        },
      },
      {
        id: 'ck9ld2skk2cjn0720d5s33uxo',
        createdAt: '2020-04-29T13:14:37.942Z',
        updatedAt: '2020-05-06T12:03:29.748Z',
        url: null,
        filename: 'OpenSans-regular.ttf',
        filetype: 'font/ttf',
        filesize: null,
        visibility: 'PUBLIC',
        use: null,
        language: {
          id: 'ck2lzfx710hkq07206thus6pt',
          languageCode: 'en',
          locale: 'en-us',
          textDirection: 'LTR',
          displayName: 'English',
          nativeName: 'English',
        },
      },
    ],
    categories: [
      {
        id: 'ck2lzgu1c0re307202dlrnue2',
        translations: [
          {
            id: 'ck2lzfxab0hls0720o2sjmoqw',
            name: 'about america',
            language: {
              id: 'ck2lzfx710hkq07206thus6pt',
              languageCode: 'en',
              locale: 'en-us',
              textDirection: 'LTR',
              displayName: 'English',
              nativeName: 'English',
            },
          },
          {
            id: 'ck2lzfxbe0hlz0720qou6kr5x',
            name: 'conozca Estados Unidos',
            language: {
              id: 'ck2lzfx7o0hl707205uteku77',
              languageCode: 'es',
              locale: 'es-es',
              textDirection: 'LTR',
              displayName: 'Spanish',
              nativeName: 'Español',
            },
          },
        ],
      },
    ],
    tags: [
      {
        id: 'ck2lzgu5e0rhu07207x85lxmb',
        translations: [
          {
            id: 'ck2lzgiwy0nx40720sedxm612',
            name: 'biomedical science',
            language: {
              id: 'ck2lzfx710hkq07206thus6pt',
              languageCode: 'en',
              locale: 'en-us',
              textDirection: 'LTR',
              displayName: 'English',
              nativeName: 'English',
            },
          },
          {
            id: 'ck2lzgixn0nxb072018rszcc5',
            name: 'ciencia Biomedica',
            language: {
              id: 'ck2lzfx7o0hl707205uteku77',
              languageCode: 'es',
              locale: 'es-es',
              textDirection: 'LTR',
              displayName: 'Spanish',
              nativeName: 'Español',
            },
          },
        ],
      },
    ],
  },
};
