export const mockData = {
  teamProjects: {
    graphics: [
      {
        alt: '',
        assetPath: 'social_media/2021/04/commons.america.gov_ckn8z9w660oy50861lwblye3w',
        author: {
          id: 'ck80d14os00150888zfvwrmqc',
          firstName: 'Jane',
          lastName: 'Doe',
          __typename: 'User',
        },
        categories: [],
        copyright: 'COPYRIGHT',
        createdAt: '2021-04-08T14:30:53.210Z',
        descInternal: {
          content: '',
          id: 'ckn8z9w6x0oy708610gy0qysz',
          visibility: 'INTERNAL',
          __typename: 'ContentField',
        },
        descPublic: {
          content: '',
          id: 'ckn8z9w6n0oy6086172z9jgto',
          visibility: 'PUBLIC',
          __typename: 'ContentField',
        },
        id: 'ckn8z9w660oy50861lwblye3w',
        images: [],
        publishedAt: null,
        status: 'DRAFT',
        tags: [],
        team: {
          contentTypes: ['VIDEO', 'GRAPHIC'],
          id: 'ck80ddxkv005a0888zu34z9w1',
          name: 'GPA Editorial & Design',
          __typename: 'Team',
        },
        title: 'Mountain',
        type: 'SOCIAL_MEDIA',
        updatedAt: '2021-04-08T14:30:53.316Z',
        visibility: 'PUBLIC',
        __typename: 'GraphicProject',
      },
    ],
    videos: [
      {
        id: 'ck990wnr705ne0788lwfvaep7',
        createdAt: '2020-04-20T22:00:42.307Z',
        updatedAt: '2020-04-20T22:00:42.307Z',
        team: {
          id: 'ck80ddxkt00550888sv0cc0vw',
          name: 'GPA Video',
          __typename: 'Team',
        },
        author: {
          id: 'ck80d14os00150888zfvwrmqc',
          firstName: 'Jane',
          lastName: 'Doe',
          __typename: 'User',
        },
        projectTitle: 'Test 2',
        status: 'DRAFT',
        visibility: 'PUBLIC',
        thumbnails: [],
        categories: [],
        __typename: 'VideoProject',
      },
      {
        id: 'ck990vslc05n40788x7ocpml9',
        createdAt: '2020-04-20T22:00:01.920Z',
        updatedAt: '2020-04-20T22:00:01.920Z',
        team: {
          id: 'ck80ddxkt00550888sv0cc0vw',
          name: 'GPA Video',
          __typename: 'Team',
        },
        author: {
          id: 'ck80d14os00150888zfvwrmqc',
          firstName: 'John',
          lastName: 'Doe',
          __typename: 'User',
        },
        projectTitle: 'Test 2',
        status: 'DRAFT',
        visibility: 'PUBLIC',
        thumbnails: [],
        categories: [],
        __typename: 'VideoProject',
      },
    ],
  },
};

export const mockNormalizedReturn = [
  {
    __typename: 'GraphicProject',
    id: 'ckn8z9w660oy50861lwblye3w',
    alt: 'Mountain',
    author: 'Jane Doe',
    categories: '',
    copyright: 'COPYRIGHT',
    createdAt: '2021-04-08T14:30:53.210Z',
    descPublic: {
      content: '',
      id: 'ckn8z9w6n0oy6086172z9jgto',
      visibility: 'PUBLIC',
      __typename: 'ContentField',
    },
    descInternal: {
      content: '',
      id: 'ckn8z9w6x0oy708610gy0qysz',
      visibility: 'INTERNAL',
      __typename: 'ContentField',
    },
    images: [],
    projectTitle: 'Mountain',
    projectType: 'SOCIAL_MEDIA',
    status: 'DRAFT',
    supportFiles: [],
    team: 'GPA Editorial & Design',
    thumbnail: { signedUrl: '', alt: '' },
    updatedAt: '2021-04-08T14:30:53.316Z',
    visibility: 'PUBLIC',
  },
  {
    __typename: 'VideoProject',
    id: 'ck990wnr705ne0788lwfvaep7',
    createdAt: '2020-04-20T22:00:42.307Z',
    updatedAt: '2020-04-20T22:00:42.307Z',
    alt: undefined,
    author: 'Jane Doe',
    categories: '',
    copyright: '',
    descPublic: '',
    descInternal: '',
    images: [],
    projectTitle: 'Test 2',
    projectType: '',
    team: 'GPA Video',
    status: 'DRAFT',
    supportFiles: [],
    visibility: 'PUBLIC',
    thumbnail: { signedUrl: '', alt: '' },
  },
  {
    __typename: 'VideoProject',
    id: 'ck990vslc05n40788x7ocpml9',
    createdAt: '2020-04-20T22:00:01.920Z',
    updatedAt: '2020-04-20T22:00:01.920Z',
    alt: undefined,
    categories: '',
    author: 'John Doe',
    copyright: '',
    descPublic: '',
    descInternal: '',
    images: [],
    projectTitle: 'Test 2',
    projectType: '',
    team: 'GPA Video',
    status: 'DRAFT',
    supportFiles: [],
    visibility: 'PUBLIC',
    thumbnail: { signedUrl: '', alt: '' },
  },
];

export const mockProjects = {
  docProject: {
    __typename: 'DocumentFile',
    title: 'Doc Title',
  },
  packageProject: {
    __typename: 'Package',
    title: 'Package Title',
  },
  videoProject: {
    __typename: 'VideoProject',
    projectTitle: 'Video Title',
  },
  nullProject: {
    __typename: 'null',
    title: 'Null Title',
  },
};
