// Hard coded list of bureaus/offices so the global store is always populated with this
// Needed for server rendering of the results page - the query filters the global bureasOffices list to check if
// a bureaus selection is a bureau or office and sets the filter accordingly
// query.js (ln. 219)

const INITIAL_STATE = {
  error: false,
  list: [
    { display_name: 'Office of the Chief of Protocol', key: 'Office of the Chief of Protocol', isBureau: true, submenu: 'document' },
    { display_name: 'Office of the Coordinator for Cyber Issues', key: 'Office of the Coordinator for Cyber Issues', isBureau: true, submenu: 'document' },
    { display_name: 'Office of the Legal Adviser', key: 'Office of the Legal Adviser', isBureau: true, submenu: 'document' },
    { display_name: 'Office of U.S. Foreign Assistance Resources', key: 'Office of U.S. Foreign Assistance Resources', isBureau: true, submenu: 'document' },
    { display_name: 'Under Secretary for Arms Control and International Security', key: 'Under Secretary for Arms Control and International Security', isBureau: true, submenu: 'document' },
    { display_name: 'Under Secretary for Civilian Security, Democracy, and Human Rights', key: 'Under Secretary for Civilian Security, Democracy, and Human Rights', isBureau: true, submenu: 'document' },
    { display_name: 'Under Secretary for Economic Growth, Energy, and the Environment', key: 'Under Secretary for Economic Growth, Energy, and the Environment', isBureau: true, submenu: 'document' },
    { display_name: 'Under Secretary for Management', key: 'Under Secretary for Management', isBureau: true, submenu: 'document' },
    { display_name: 'Under Secretary for Political Affairs', key: 'Under Secretary for Political Affairs', isBureau: true, submenu: 'document' },
    { display_name: 'Under Secretary for Public Diplomacy and Public Affairs', key: 'Under Secretary for Public Diplomacy and Public Affairs', isBureau: true, submenu: 'document' },
    { display_name: 'Office of Global Criminal Justice', key: 'Office of Global Criminal Justice', isBureau: true, submenu: 'document' },
    { display_name: 'Office of International Religious Freedom', key: 'Office of International Religious Freedom', isBureau: true, submenu: 'document' },
    { display_name: 'Office of the Special Envoy to Monitor and Combat Anti-Semitism', key: 'Office of the Special Envoy to Monitor and Combat Anti-Semitism', isBureau: true, submenu: 'document' },
    { display_name: 'Office to Monitor and Combat Trafficking in Persons', key: 'Office to Monitor and Combat Trafficking in Persons', isBureau: true, submenu: 'document' },
    { display_name: 'Office of the Science and Technology Advisor', key: 'Office of the Science and Technology Advisor', isBureau: true, submenu: 'document' },
    { display_name: 'Foreign Service Institute', key: 'Foreign Service Institute', isBureau: true, submenu: 'document' },
    { display_name: 'Office of Emergencies in the Diplomatic and Consular Service', key: 'Office of Emergencies in the Diplomatic and Consular Service', isBureau: true, submenu: 'document' },
    { display_name: 'Office of Foreign Missions', key: 'Office of Foreign Missions', isBureau: true, submenu: 'document' },
    { display_name: 'Office of Management Strategy and Solutions', key: 'Office of Management Strategy and Solutions', isBureau: true, submenu: 'document' },
    { display_name: 'Global Engagement Center', key: 'Global Engagement Center', isBureau: true, submenu: 'document' },
    { display_name: 'Office of Policy, Planning, and Resources', key: 'Office of Policy, Planning, and Resources', isBureau: true, submenu: 'document' },
    { display_name: 'Asia-Pacific Economic Cooperation', key: 'Asia-Pacific Economic Cooperation', isBureau: true, submenu: 'document' },
    { display_name: 'Bureau of Administration', key: 'Bureau of Administration', isBureau: true, submenu: 'document' },
    { display_name: 'Bureau of African Affairs', key: 'Bureau of African Affairs', isBureau: true, submenu: 'document' },
    { display_name: 'Bureau of Arms Control, Verification and Compliance', key: 'Bureau of Arms Control, Verification and Compliance', isBureau: true, submenu: 'document' },
    { display_name: 'Bureau of Budget and Planning', key: 'Bureau of Budget and Planning', isBureau: true, submenu: 'document' },
    { display_name: 'Bureau of Conflict and Stabilization Operations', key: 'Bureau of Conflict and Stabilization Operations', isBureau: true, submenu: 'document' },
    { display_name: 'Bureau of Consular Affairs', key: 'Bureau of Consular Affairs', isBureau: true, submenu: 'document' },
    { display_name: 'Bureau of Counterterrorism', key: 'Bureau of Counterterrorism', isBureau: true, submenu: 'document' },
    { display_name: 'Bureau of Democracy, Human Rights, and Labor', key: 'Bureau of Democracy, Human Rights, and Labor', isBureau: true, submenu: 'document' },
    { display_name: 'Bureau of Diplomatic Security', key: 'Bureau of Diplomatic Security', isBureau: true, submenu: 'document' },
    { display_name: 'Bureau of East Asian and Pacific Affairs', key: 'Bureau of East Asian and Pacific Affairs', isBureau: true, submenu: 'document' },
    { display_name: 'Bureau of Economic and Business Affairs', key: 'Bureau of Economic and Business Affairs', isBureau: true, submenu: 'document' },
    { display_name: 'Bureau of Educational and Cultural Affairs', key: 'Bureau of Educational and Cultural Affairs', isBureau: true, submenu: 'document' },
    { display_name: 'Bureau of Energy Resources', key: 'Bureau of Energy Resources', isBureau: true, submenu: 'document' },
    { display_name: 'Bureau of European and Eurasian Affairs', key: 'Bureau of European and Eurasian Affairs', isBureau: true, submenu: 'document' },
    { display_name: 'Bureau of Global Public Affairs', key: 'Bureau of Global Public Affairs', isBureau: true, submenu: 'document' },
    { display_name: 'Bureau of Human Resources', key: 'Bureau of Human Resources', isBureau: true, submenu: 'document' },
    { display_name: 'Bureau of Information Resource Management', key: 'Bureau of Information Resource Management', isBureau: true, submenu: 'document' },
    { display_name: 'Bureau of Intelligence and Research', key: 'Bureau of Intelligence and Research', isBureau: true, submenu: 'document' },
    { display_name: 'Bureau of International Narcotics and Law Enforcement Affairs', key: 'Bureau of International Narcotics and Law Enforcement Affairs', isBureau: true, submenu: 'document' },
    { display_name: 'Bureau of International Organization Affairs', key: 'Bureau of International Organization Affairs', isBureau: true, submenu: 'document' },
    { display_name: 'Bureau of International Security and Nonproliferation', key: 'Bureau of International Security and Nonproliferation', isBureau: true, submenu: 'document' },
    { display_name: 'Bureau of Legislative Affairs', key: 'Bureau of Legislative Affairs', isBureau: true, submenu: 'document' },
    { display_name: 'Bureau of Near Eastern Affairs', key: 'Bureau of Near Eastern Affairs', isBureau: true, submenu: 'document' },
    { display_name: 'Bureau of Overseas Buildings Operations', key: 'Bureau of Overseas Buildings Operations', isBureau: true, submenu: 'document' },
    { display_name: 'Bureau of Oceans and International Environmental and Scientific Affairs', key: 'Bureau of Oceans and International Environmental and Scientific Affairs', isBureau: true, submenu: 'document' },
    { display_name: 'Bureau of Political-Military Affairs', key: 'Bureau of Political-Military Affairs', isBureau: true, submenu: 'document' },
    { display_name: 'Bureau of Population, Refugees, and Migration', key: 'Bureau of Population, Refugees, and Migration', isBureau: true, submenu: 'document' },
    { display_name: 'Bureau of South and Central Asian Affairs', key: 'Bureau of South and Central Asian Affairs', isBureau: true, submenu: 'document' },
    { display_name: 'Bureau of the Comptroller and Global Financial Service', key: 'Bureau of the Comptroller and Global Financial Service', isBureau: true, submenu: 'document' },
    { display_name: 'Bureau of Western Hemisphere Affairs', key: 'Bureau of Western Hemisphere Affairs', isBureau: true, submenu: 'document' },
    { display_name: 'Counselor of the Department', key: 'Counselor of the Department', isBureau: true, submenu: 'document' },
    { display_name: 'Deputy Secretary of State', key: 'Deputy Secretary of State', isBureau: true, submenu: 'document' },
    { display_name: 'Office of Inspector General', key: 'Office of Inspector General', isBureau: true, submenu: 'document' },
    { display_name: 'The Secretary of State', key: 'The Secretary of State', isBureau: true, submenu: 'document' },
    { display_name: 'United States Agency for International Development', key: 'United States Agency for International Development', isBureau: true, submenu: 'document' },
    { display_name: 'United States Mission to the United Nations', key: 'United States Mission to the United Nations', isBureau: true, submenu: 'document' },
    { display_name: 'Office of Treaty Affairs', key: 'Office of Treaty Affairs', submenu: 'document' },
    { display_name: 'Office of Logistics Management', key: 'Office of Logistics Management', submenu: 'document' },
    { display_name: 'Office of Overseas Schools', key: 'Office of Overseas Schools', submenu: 'document' },
    { display_name: 'Office of Procurement Executive', key: 'Office of Procurement Executive', submenu: 'document' },
    { display_name: 'Office of the Special Envoy for the Great Lakes Region of Africa', key: 'Office of the Special Envoy for the Great Lakes Region of Africa', submenu: 'document' },
    { display_name: 'Division for Counter Threat Finance and Sanctions', key: 'Division for Counter Threat Finance and Sanctions', submenu: 'document' },
    { display_name: 'Office of Global Social Media', key: 'Office of Global Social Media', submenu: 'document' },
  ],
  loading: false,
};

export default ( state = INITIAL_STATE, action ) => {
  switch ( action.type ) {
    default:
      return state;
  }
};
