export const graphicElasticMock = [
  {
    _source: {
      id: 'ck8h90w6x030l0765onryiqdt',
      site: 'commons.america.gov',
      type: 'graphic',
      projectType: 'Social Media Graphic',
      published: '2020-03-22T15:15:00.074Z',
      modified: '2020-04-02T15:15:00.074Z',
      visibility: 'PUBLIC',
      owner: 'GPA Editorial & Design',
      alt: 'Some alt text here...',
      desc: 'Secretary Pompeo outlined 12 requirements for Iran\'s regime to act like a normal state. With the November 4th sanctions deadline, here are reminders for the regime, starting with #12: Declare prior military dimensions of your nuclear program & abandon such work.',
      descInternal: 'Internal description....',
      copyright: 'COPYRIGHT',
      images: [
        {
          title: 'Mon titre graphique',
          visibility: 'PUBLIC',
          url: 'https://cdp-video-tst.s3.amazonaws.com/2020/04/commons.america.gov_ck8h90w6x030l0765onryiqdt/CAPTIONS_Made_in_America_FRENCH_Twitter_Output.png',
          language: {
            language_code: 'fr',
            text_direction: 'ltr',
            locale: 'fr-fr',
            display_name: 'French',
            native_name: 'French',
          },
          filename: 'CAPTIONS_Made_in_America_FRENCH_Twitter_Output.png',
          alt: 'Texte alternatif français',
          filesize: '600 MB',
          width: 800,
          height: 600,
          social: ['Twitter'],
          style: 'Quote',
        },
        {
          title: 'Mon titre graphique FACEBOOK',
          visibility: 'PUBLIC',
          url: 'https://cdp-video-tst.s3.amazonaws.com/2020/04/commons.america.gov_ck8h90w6x030l0765onryiqdt/CAPTIONS_Made_in_America_FRENCH_Facebook_Output.png',
          language: {
            language_code: 'fr',
            text_direction: 'ltr',
            locale: 'fr-fr',
            display_name: 'French',
            native_name: 'French',
          },
          filename: 'CAPTIONS_Made_in_America_FRENCH_Facebook_Output.png',
          alt: 'Texte alternatif français',
          filesize: '600 MB',
          width: 800,
          height: 600,
          social: ['Facebook', 'Instagram'],
          style: 'Quote',
        },
        {
          title: 'My graphic title',
          visibility: 'PUBLIC',
          url: 'https://cdp-video-tst.s3.amazonaws.com/2020/04/commons.america.gov_ck8h90w6x030l0765onryiqdt/CAPTIONS_Made_in_America_English_Output.png',
          language: {
            language_code: 'en',
            text_direction: 'ltr',
            locale: 'en-us',
            display_name: 'English',
            native_name: 'English',
          },
          filename: 'CAPTIONS_Made_in_America_English_Output.png',
          alt: 'English alt text',
          filesize: '600 MB',
          width: 800,
          height: 600,
          social: ['Twitter'],
          style: 'Quote',
        },
      ],
      supportFiles: [
        {
          visibility: 'INTERNAL',
          editable: true,
          url: 'https://cdp-video-tst.s3.amazonaws.com/2020/04/commons.america.gov_ck8h90w6x030l0765onryiqdt/CAPTIONS_Made_in_America_English_Output.psd',
          language: {
            language_code: 'en',
            text_direction: 'ltr',
            locale: 'en-us',
            display_name: 'English',
            native_name: 'English',
          },
        },
        {
          visibility: 'INTERNAL',
          editable: true,
          url: 'https://cdp-video-tst.s3.amazonaws.com/2020/04/commons.america.gov_ck8h90w6x030l0765onryiqdt/CAPTIONS_Made_in_America_English_Output.ai',
          language: {
            language_code: 'en',
            text_direction: 'ltr',
            locale: 'en-us',
            display_name: 'English',
            native_name: 'English',
          },
        },
        {
          visibility: 'INTERNAL',
          editable: true,
          url: 'https://cdp-video-tst.s3.amazonaws.com/2020/04/commons.america.gov_ck8h90w6x030l0765onryiqdt/CAPTIONS_Made_in_America_English_Output.png',
          language: {
            language_code: 'en',
            text_direction: 'ltr',
            locale: 'en-us',
            display_name: 'English',
            native_name: 'English',
          },
        },
        {
          visibility: 'INTERNAL',
          editable: true,
          url: 'https://cdp-video-tst.s3.amazonaws.com/2020/04/commons.america.gov_ck8h90w6x030l0765onryiqdt/CAPTIONS_Made_in_America_French_Output.psd',
          language: {
            language_code: 'fr',
            text_direction: 'ltr',
            locale: 'fr-fr',
            display_name: 'French',
            native_name: 'French',
          },
        },
        {
          visibility: 'INTERNAL',
          editable: true,
          url: 'https://cdp-video-tst.s3.amazonaws.com/2020/04/commons.america.gov_ck8h90w6x030l0765onryiqdt/CAPTIONS_Made_in_America_French_Output.ai',
          language: {
            language_code: 'fr',
            text_direction: 'ltr',
            locale: 'fr-fr',
            display_name: 'French',
            native_name: 'French',
          },
        },
        {
          visibility: 'INTERNAL',
          editable: false,
          url: 'https://cdp-video-tst.s3.amazonaws.com/2020/04/commons.america.gov_ck8h90w6x030l0765onryiqdt/CAPTIONS_Made_in_America_French_Output.doc',
          language: {
            language_code: 'fr',
            text_direction: 'ltr',
            locale: 'fr-fr',
            display_name: 'French',
            native_name: 'French',
          },
        },
        {
          visibility: 'INTERNAL',
          editable: false,
          url: 'https://cdp-video-tst.s3.amazonaws.com/2020/04/commons.america.gov_ck8h90w6x030l0765onryiqdt/CAPTIONS_Made_in_America_French_Output.pdf',
          language: {
            language_code: 'fr',
            text_direction: 'ltr',
            locale: 'fr-fr',
            display_name: 'French',
            native_name: 'French',
          },
        },
        {
          visibility: 'INTERNAL',
          editable: false,
          url: 'https://cdp-video-tst.s3.amazonaws.com/2020/04/commons.america.gov_ck8h90w6x030l0765onryiqdt/CAPTIONS_Made_in_America_English_Output.doc',
          language: {
            language_code: 'en',
            text_direction: 'ltr',
            locale: 'en-us',
            display_name: 'English',
            native_name: 'English',
          },
        },
        {
          visibility: 'INTERNAL',
          editable: false,
          url: 'https://cdp-video-tst.s3.amazonaws.com/2020/04/commons.america.gov_ck8h90w6x030l0765onryiqdt/CAPTIONS_Made_in_America_English_Output.pdf',
          language: {
            language_code: 'en',
            text_direction: 'ltr',
            locale: 'en-us',
            display_name: 'English',
            native_name: 'English',
          },
        },
      ],
      tags: [
        {
          name: 'biomedical science',
          id: 'KBb5K3EB-L8EaltkVCV8',
        },
      ],
      categories: [
        {
          name: 'science & technology',
          id: 'TBb5K3EB-L8EaltkViXQ',
        },
      ],
    },
  },
];
